name: Run Notebook

on:
  workflow_dispatch: {}      # permite disparo via API/Apps Script
  # (se quiser agendar direto no GitHub, descomente abaixo)
  # schedule:
  #   - cron: "0 11 * * *"   # 08:00 BRT (GitHub usa UTC)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install papermill jupyter
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute notebook with Papermill
        run: |
          papermill teste_scheduler.ipynb output.ipynb

      - name: Upload executed notebook
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebook
          path: output.ipynb
